/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fenetre_ajout (void);
GtkWidget* create_fenetre_afficher (void);
GtkWidget* create_fenetre_modif (void);
GtkWidget* create_window_rech (void);
GtkWidget* create_stat (void);
